# ==============================================================================
# STAGE 1: Dependencies (`deps`)
# ==============================================================================
# We use Alpine Linux as the base image for its incredibly small size,
# which keeps our final Docker image lightweight and secure.
FROM node:20-alpine AS deps

# Alpine doesn't include the standard C library (glibc) out of the box.
# `libc6-compat` is needed for certain Node.js native add-ons to compile and run properly.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# We only copy the package.json and package-lock.json files first.
# This ensures that Docker caches the installed dependencies unless these two files change,
# significantly speeding up the build process.
COPY package.json package-lock.json* ./
RUN npm ci

# ==============================================================================
# STAGE 2: Builder (`builder`)
# ==============================================================================
# This stage builds the Next.js application using the dependencies installed in Stage 1.
FROM node:20-alpine AS builder
WORKDIR /app

# Copy the completely installed node_modules from the `deps` stage.
COPY --from=deps /app/node_modules ./node_modules

# Copy the rest of the application source code into the container.
COPY . .

# Disable Next.js telemetry (anonymous analytics) during the build process to speed it up.
ENV NEXT_TELEMETRY_DISABLED=1

# Run the build process. Next.js will compile the app into a `.next/standalone` directory
# (as configured in next.config.mjs), which contains only the files necessary to run the app.
RUN npm run build

# ==============================================================================
# STAGE 3: Production Runner (`runner`)
# ==============================================================================
# This is the final stage. Only the built assets are brought here, keeping the final image tiny.
FROM node:20-alpine AS runner
WORKDIR /app

# Set Node environment to production for optimal performance.
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# For security reasons, we should never run the application as the root user.
# We create a dedicated non-root user `nextjs` and group `nodejs`.
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Create the `.next` directory and assign ownership to our non-root user.
# This allows Next.js to properly write its prerender cache during runtime.
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Copy the optimized standalone build and static assets from the `builder` stage.
# We also change ownership of these files to our non-root user simultaneously.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Copy initial dummy/default data so that the JSON database isn't completely empty
# on the very first start.
COPY --from=builder --chown=nextjs:nodejs /app/data-seed ./data

# Mount a persistent volume at `/app/data` to ensure that our JSON database and uploads
# are not lost when the Docker container is stopped or recreated.
VOLUME ["/app/data"]

# Switch from the root user to our secure, unprivileged user.
USER nextjs

# Expose port 3000 to allow the host machine to communicate with the Next.js app.
EXPOSE 3000

# Tell Next.js to listen on all network interfaces (0.0.0.0) instead of just localhost,
# which is necessary inside a Docker container.
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Start the application using the standalone server file generated by Next.js.
CMD ["node", "server.js"]
